"""
Random agent names for display purposes.
Adds a bit of personality to the AI responses.
"""

import random

AGENT_NAMES = [
    "Aristotle",
    "Plato",
    "Socrates",
    "Isaac Newton",
    "Albert Einstein",
    "Leonardo da Vinci",
    "Galileo Galilei",
    "Charles Darwin",
    "Nikola Tesla",
    "Johannes Kepler",
    "Gottfried Wilhelm Leibniz",
    "Blaise Pascal",
    "Rene Descartes",
    "Immanuel Kant",
    "David Hume",
    "Baruch Spinoza",
    "John Locke",
    "Georg Wilhelm Friedrich Hegel",
    "Friedrich Nietzsche",
    "Karl Marx",
    "Alan Turing",
    "John von Neumann",
    "Kurt Godel",
    "Bertrand Russell",
    "Ludwig Wittgenstein",
    "Claude Shannon",
    "Richard Feynman",
    "Stephen Hawking",
    "James Clerk Maxwell",
    "Michael Faraday",
    "Euclid",
    "Archimedes",
    "Pythagoras",
    "Hippocrates",
    "Eratosthenes",
    "Avicenna",
    "Averroes",
    "Al-Khwarizmi",
    "Omar Khayyam",
    "Ibn Khaldun",
    "Confucius",
    "Laozi",
    "Zhuangzi",
    "Mencius",
    "Sun Tzu",
    "Zhu Xi",
    "Wang Yangming",
    "Zhang Heng",
    "Shen Kuo",
    "Li Shizhen",
    "Hypatia",
    "Heron of Alexandria",
    "Plotinus",
    "Proclus",
    "Thomas Aquinas",
    "Roger Bacon",
    "William of Ockham",
    "Nicolaus Copernicus",
    "Francis Bacon",
    "Giordano Bruno",
    "Voltaire",
    "Jean-Jacques Rousseau",
    "Denis Diderot",
    "Adam Smith",
    "Thomas Hobbes",
    "Montesquieu",
    "Pierre-Simon Laplace",
    "Antoine Lavoisier",
    "Augustin-Louis Cauchy",
    "Carl Friedrich Gauss",
    "Leonhard Euler",
    "Joseph Fourier",
    "Pierre de Fermat",
    "Blaise de Vigenere",
    "Gregor Mendel",
    "Louis Pasteur",
    "Marie Curie",
    "Max Planck",
    "Niels Bohr",
    "Werner Heisenberg",
    "Erwin Schrodinger",
    "Paul Dirac",
    "Enrico Fermi",
    "Srinivasa Ramanujan",
    "Andrey Kolmogorov",
    "Norbert Wiener",
    "John Nash",
    "Benoit Mandelbrot",
    "Edward Witten",
    "Roger Penrose",
    "Rabindranath Tagore",
    "Johann Wolfgang von Goethe",
    "William Shakespeare",
    "Dante Alighieri",
    "Homer",
    "Miguel de Cervantes",
    "Leo Tolstoy",
    "Fyodor Dostoevsky",
    "Victor Hugo",
    "Johann Sebastian Bach",
    "Ludwig van Beethoven",
    "Wolfgang Amadeus Mozart",
    "Joseph Haydn",
    "Claude Debussy",
    "Igor Stravinsky",
    "Michelangelo",
    "Raphael",
    "Donatello",
    "Sandro Botticelli",
    "Albrecht Durer",
    "Nicola Tesla",
    "Thomas Edison",
    "Alexander Graham Bell",
    "James Watt",
    "Michaelangelo Antonioni",
    "Buckminster Fuller",
    "Steve Jobs",
    "Steve Wozniak",
    "Bill Gates",
    "Paul Allen",
    "Benjamin Franklin",
    "Thomas Jefferson",
    "Abraham Lincoln",
    "Napoleon Bonaparte",
    "Julius Caesar",
    "Alexander the Great",
    "Marcus Aurelius",
    "Cicero",
    "Sun Yat-sen",
    "Mao Zedong",
    "Mahatma Gandhi",
    "Nelson Mandela",
    "Martin Luther King Jr.",
    "Abraham Maslow",
    "Carl Jung",
    "Sigmund Freud",
    "Jean Piaget",
    "Lev Vygotsky",
    "B. F. Skinner",
    "Noam Chomsky",
    "Hannah Arendt",
    "Karl Popper",
    "Thomas Kuhn",
    "Michel Foucault",
    "Jacques Derrida",
    "Jean-Paul Sartre",
    "Albert Camus",
    "Simone de Beauvoir",
    "Gilles Deleuze",
    "Antonio Gramsci",
    "George Orwell",
    "Aldous Huxley",
    "Ray Bradbury",
    "Isaac Asimov",
    "Arthur C. Clarke",
    "Stanislaw Lem",
    "H. G. Wells",
    "J. R. R. Tolkien",
    "C. S. Lewis",
    "Umberto Eco",
    "Nikolaus Wirth",
    "Donald Knuth",
    "Edsger Dijkstra",
    "Ken Thompson",
    "Dennis Ritchie",
    "Tim Berners-Lee",
    "Linus Torvalds",
    "Larry Page",
    "Sergey Brin",
    "Geoffrey Hinton",
    "Yoshua Bengio",
    "Yann LeCun",
    "Marvin Minsky",
    "Herbert Simon",
    "John McCarthy",
    "Ray Kurzweil",
    "Elon Musk",
    "Jeff Bezos",
    "Peter Thiel",
    "Sam Altman",
    "Thales of Miletus",
    "Anaximander",
    "Anaximenes",
    "Democritus",
    "Epicurus",
    "Zeno of Elea",
    "Pyrrho",
    "Sextus Empiricus",
    "Boethius",
    "Al-Farabi",
    "Al-Ghazali",
    "Nasir al-Din al-Tusi",
    "Jabir ibn Hayyan",
    "Li Bai",
    "Du Fu",
    "Bai Juyi",
    "Han Yu",
    "Su Shi",
    "Ouyang Xiu",
    "Sima Qian",
    "Ban Zhao",
    "Cai Lun",
    "Bi Sheng",
    "Huangdi",
    "Mozi",
    "Xunzi",
    "Han Feizi",
    "Li Si",
    "Zhang Zai",
    "Cheng Yi",
    "Cheng Hao",
    "Gu Yanwu",
    "Huang Zongxi",
    "Liang Qichao",
    "Yan Fu",
    "Hu Shi",
    "Chen Duxiu",
    "Lu Xun",
    "Qian Xuesen",
    "Yang Zhenning",
    "Chen Jingrun",
    "Hua Luogeng",
    "Terence Tao",
    "Grigori Perelman",
    "Andrew Wiles",
    "Maryam Mirzakhani",
    "Emmy Noether",
    "Ada Lovelace",
    "Sophie Germain",
    "Hypatia of Alexandria",
    "Rachel Carson",
    "Jane Goodall",
    "Margaret Mead",
    "Claude Levi-Strauss",
    "Fernand Braudel",
    "Arnold Toynbee",
    "Yuval Noah Harari",
    "Jared Diamond",
    "Nassim Nicholas Taleb",
    "Peter Drucker",
    "Max Weber",
    "Emile Durkheim",
    "Vilfredo Pareto",
    "Joseph Schumpeter",
    "Friedrich Hayek",
    "Ludwig von Mises",
    "John Maynard Keynes",
    "Amartya Sen",
    "Daniel Kahneman",
    "Herbert Marcuse",
    "Alan Greenspan",
    "George Soros",
    "Warren Buffett",
    "Charlie Munger",
    "Ray Dalio",
    "John Rockefeller",
    "Andrew Carnegie",
    "Henry Ford",
    "Nikolaus Copernicus",
    "Tycho Brahe",
    "Jan Hus",
    "Martin Luther",
    "John Calvin",
    "Erasmus",
    "Baruch Goldstein",
    "Moses Maimonides",
    "Akhenaten",
    "Hammurabi",
    "Solon",
    "Lycurgus",
    "Pericles",
    "Thucydides",
    "Herodotus",
    "Tacitus",
    "Livy",
    "Plutarch",
    "Polybius",
    "Ibn Sina",
    "Al-Biruni",
    "Al-Razi",
    "Ramon Llull",
    "Giambattista Vico",
    "Johann Heinrich Pestalozzi",
    "Friedrich Froebel",
    "Maria Montessori",
    "Rudolf Steiner",
    "Ivan Pavlov",
    "Konrad Lorenz",
    "Nikola Tinbergen",
    "Ernst Mayr",
    "Charles Lyell",
    "James Hutton",
    "Alfred Wegener",
    "John Snow",
    "Florence Nightingale",
    "Edward Jenner",
    "Jonas Salk",
    "Lin Zexu",
    "Deng Xiaoping",
    "Zhou Enlai",
]


def get_random_agent_name() -> str:
    """Get a random agent name from the list."""
    return random.choice(AGENT_NAMES)
